// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/payments" | "/admin/products" | "/admin/reviews" | "/admin/users" | "/admin/vendors" | "/categories" | "/categories/[slug]" | "/dashboard" | "/for-vendors" | "/onboarding" | "/products" | "/products/[slug]" | "/products/[slug]/review" | "/publisher" | "/publisher/billing" | "/publisher/products/new" | "/search" | "/sign-in/[[...sign-in]]" | "/sign-up/[[...sign-up]]"
type AppRouteHandlerRoutes = "/api/onboarding-sync" | "/api/razorpay/create-order" | "/api/razorpay/verify" | "/api/webhooks/clerk" | "/api/webhooks/razorpay"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin" | "/publisher"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/payments": {}
  "/admin/products": {}
  "/admin/reviews": {}
  "/admin/users": {}
  "/admin/vendors": {}
  "/api/onboarding-sync": {}
  "/api/razorpay/create-order": {}
  "/api/razorpay/verify": {}
  "/api/webhooks/clerk": {}
  "/api/webhooks/razorpay": {}
  "/categories": {}
  "/categories/[slug]": { "slug": string; }
  "/dashboard": {}
  "/for-vendors": {}
  "/onboarding": {}
  "/products": {}
  "/products/[slug]": { "slug": string; }
  "/products/[slug]/review": { "slug": string; }
  "/publisher": {}
  "/publisher/billing": {}
  "/publisher/products/new": {}
  "/search": {}
  "/sign-in/[[...sign-in]]": { "sign-in"?: string[]; }
  "/sign-up/[[...sign-up]]": { "sign-up"?: string[]; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
  "/publisher": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
