var R=require("../../../chunks/[turbopack]_runtime.js")("server/app/api/onboarding-sync/route.js")
R.c("server/chunks/node_modules__pnpm_904aff44._.js")
R.c("server/chunks/969b2_next_cc5e82f7._.js")
R.c("server/chunks/e6754_@clerk_backend_dist_2c90f84e._.js")
R.c("server/chunks/ad1d7_@clerk_nextjs_dist_esm_b22825aa._.js")
R.c("server/chunks/a5156_@clerk_shared_dist_15f4553d._.js")
R.c("server/chunks/[root-of-the-server]__68980227._.js")
R.m("[project]/.next-internal/server/app/api/onboarding-sync/route/actions.js [app-rsc] (server actions loader, ecmascript)")
R.m("[project]/node_modules/.pnpm/next@15.5.20_@babel+core@7.29.7_@playwright+test@1.61.1_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/onboarding-sync/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)")
module.exports=R.m("[project]/node_modules/.pnpm/next@15.5.20_@babel+core@7.29.7_@playwright+test@1.61.1_react-dom@19.1.0_react@19.1.0__react@19.1.0/node_modules/next/dist/esm/build/templates/app-route.js { INNER_APP_ROUTE => \"[project]/src/app/api/onboarding-sync/route.ts [app-route] (ecmascript)\" } [app-route] (ecmascript)").exports
